import {minutesAgo,healthState,collectorTime,clockDisplay,nextScrapeLabel,orderedGroups} from './logic.js';
import {ukParts,addDays,midnight,catalogueMaps,filterRows,timeline,rankings,averagePattern,patternForRows,categories,csv} from './analytics-core.js';
import {colours,plot,heatmap,rankBars,table,empty} from './analytics-charts.js';
const $=id=>document.getElementById(id), config=window.POLICE_CONFIG;
const client=(()=>{let allowed=config?.supabasePublishableKey?.startsWith('sb_publishable_');if(config?.supabasePublishableKey?.startsWith('eyJ')){try{allowed=JSON.parse(atob(config.supabasePublishableKey.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='anon';}catch{allowed=false;}}if(!allowed||!config?.supabaseUrl){$('auth-message').textContent='The website needs its public Supabase connection settings. Contact Owen.';$('auth-submit').disabled=true;throw new Error('Invalid public browser configuration.');}return window.supabase.createClient(config.supabaseUrl,config.supabasePublishableKey);})();
let session=null,access=false,accessBusy=false,accessTimer,accessUntil=0,accessWall=0,epoch=0,loadController=null;
let health=null,healthAt=0,allRows=[],loaded=false,loadedRange=null,maps,forces=[],patches=[],archive={},exports=new Map();
const selected={forces:new Set(),patches:new Set(),groups:new Set()};
let saved={};try{saved=JSON.parse(localStorage.getItem('police-data-preferences')||'{}');}catch{}
const now=()=>collectorTime(health,healthAt);
function msg(id,text){$(id).textContent=text;}
function dateLabel(ms){return new Date(ms).toLocaleString('en-GB',{timeZone:'Europe/London',dateStyle:'medium',timeStyle:'short'});}
async function bounded(request){let timer;try{return await Promise.race([request,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('The connection timed out.')),10000);})]);}finally{clearTimeout(timer);}}
function permitted(){return access&&performance.now()<accessUntil&&Date.now()<accessWall;}
function clearData(){epoch++;loadController?.abort();loadController=null;clearTimeout(accessTimer);access=false;allRows=[];loaded=false;archive={};exports.clear();for(const id of ['metric-total','metric-forces','metric-average','metric-average-detail','metric-peak','metric-peak-detail','load-status','coverage-note'])msg(id,'');$('analytics').hidden=true;$('charts').hidden=true;for(const id of ['timeline-chart','timeline-table','timeline-legend','average-legend','hour-chart','weekday-chart','heatmap-chart','ranking-chart','ranking-table','locations-chart'])$(id).replaceChildren();}
function waiting(reason){$('waiting').hidden=false;$('auth').hidden=true;const labels={approval:['Awaiting approval','Owen needs to approve your account.'],verification:['Verify your email','Follow the verification email from Supabase Auth.'],paused:['Access paused','Owen has paused your account.'],outside_shift:['Outside your allowed hours','Come back during your approved shifts.'],blocked:['Access unavailable at this time','This period is blocked for your account.'],error:['Connection interrupted','Access could not be checked. Reconnecting automatically…'],check:['Checking access','Checking your account and allowed hours…']};const text=labels[reason]||labels.approval;msg('waiting-title',text[0]);msg('waiting-detail',text[1]);}
function renderHealth(){const online=healthState(health,healthAt);$('health').className='health '+(online?'online':'offline');msg('health-label',online?'Online':'Offline');msg('health-detail',health?.last_data_at?'Updated '+minutesAgo(health.last_data_at):'No collector update');const c=clockDisplay(now());msg('current-time',c.text);$('current-time').classList.toggle('deadline',c.red);msg('next-scrape',nextScrapeLabel(health,healthAt));}
async function pollHealth(){try{const r=await bounded(client.rpc('desk_collector_health'));health=r.error?null:r.data;healthAt=Date.now();}catch{health=null;}renderHealth();}
async function checkAccess(){if(!session||accessBusy)return;accessBusy=true;const version=epoch,started=performance.now();try{const r=await bounded(client.rpc('desk_my_access'));if(version!==epoch)return;if(r.error||typeof r.data?.allowed!=='boolean')throw new Error('Access unavailable');if(!r.data.allowed){clearData();waiting(r.data.reason);return;}const delay=Math.max(0,Math.min(30000,Date.parse(r.data.check_at)-Date.parse(r.data.server_now)-(performance.now()-started)));if(!delay)throw new Error('Access expired');const opening=!access;access=true;accessUntil=performance.now()+delay;accessWall=Date.now()+delay;clearTimeout(accessTimer);accessTimer=setTimeout(()=>{clearData();waiting('check');checkAccess();},delay);$('auth').hidden=true;$('waiting').hidden=true;$('analytics').hidden=false;if(opening){await prepare();if(version===epoch&&permitted())loadData();}}catch{if(version===epoch){clearData();waiting('error');}}finally{accessBusy=false;}}
function onSession(next){const changed=session?.user.id!==next?.user.id;session=next;$('account').hidden=!next;msg('email',next?.user.email||'');if(changed||!next)clearData();if(!next){$('waiting').hidden=true;$('auth').hidden=false;return;}checkAccess();}
$('auth-form').onsubmit=async e=>{e.preventDefault();$('auth-submit').disabled=true;msg('auth-message','');try{const r=await client.auth.signInWithPassword({email:$('auth-email').value.trim(),password:$('password').value});if(r.error)throw r.error;$('password').value='';}catch(e){msg('auth-message',e.message);}finally{$('auth-submit').disabled=false;}};
$('signout').onclick=async()=>{clearData();session=null;onSession(null);await client.auth.signOut({scope:'local'});};
$('check-access').onclick=checkAccess;
function save(){try{localStorage.setItem('police-data-preferences',JSON.stringify({basis:$('basis').value,range:$('range').value,from:$('date-from').value,to:$('date-to').value,bucket:$('bucket').value,breakdown:$('breakdown').value,chart:$('chart-type').value,forces:[...selected.forces],patches:[...selected.patches],groups:[...selected.groups]}));}catch{}}
function picker(kind,items){const root=$(kind+'-picker'),choices=root.querySelector('.choices');choices.replaceChildren();selected[kind]=new Set((saved[kind]||[]).filter(id=>items.some(i=>i[0]===id)));for(const [id,name]of items){const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=id;box.checked=selected[kind].has(id);box.onchange=()=>{box.checked?selected[kind].add(id):selected[kind].delete(id);counts();save();render();};label.append(box,document.createTextNode(name));choices.append(label);}root.querySelector('input[type=search]').oninput=e=>{const q=e.target.value.toLowerCase();for(const label of choices.children)label.hidden=!label.textContent.toLowerCase().includes(q);};for(const button of root.querySelectorAll('[data-select]'))button.onclick=()=>{for(const box of choices.querySelectorAll('input')){box.checked=button.dataset.select==='all';box.checked?selected[kind].add(box.value):selected[kind].delete(box.value);}counts();save();render();};}
function counts(){for(const k of Object.keys(selected))$(k+'-picker').querySelector('summary span').textContent=selected[k].size?'('+selected[k].size+' selected)':'(all)';msg('filter-summary',[...Object.entries(selected)].filter(([k,v])=>v.size).map(([k,v])=>v.size+' '+k).join(' · ')||'All forces and coverage areas');}
async function prepare(){if(!maps){[forces,patches]=await Promise.all([fetch('./forces.json').then(r=>r.json()),fetch('./patches.json').then(r=>r.json())]);maps=catalogueMaps(forces,patches);picker('forces',[...maps.forces].sort((a,b)=>a[1].localeCompare(b[1])));picker('patches',[...maps.patches].sort((a,b)=>a[1].localeCompare(b[1])));picker('groups',orderedGroups(patches).map(g=>[g,g]));for(const [id,key]of [['basis','basis'],['range','range'],['bucket','bucket'],['breakdown','breakdown'],['chart-type','chart']])if([...$(id).options].some(o=>o.value===saved[key]))$(id).value=saved[key];if(saved.from)$('date-from').value=saved.from;if(saved.to)$('date-to').value=saved.to;counts();}
 for(const basis of ['first_seen_at','published_at']){const r=await bounded(client.from('police_releases').select(basis).order(basis).limit(1));if(r.error)throw r.error;archive[basis]=r.data[0]?.[basis]||null;}setDates();}
function setDates(){const range=$('range').value,today=ukParts(now()).date;if(range==='custom')return;$('date-to').value=today;$('date-from').value=range==='all'?(archive[$('basis').value]?ukParts(Date.parse(archive[$('basis').value])).date:today):addDays(today,1-Number(range));}
function options(){const start=$('date-from').value,end=$('date-to').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||end<start)throw new Error('Choose a valid start and end date.');const from=midnight(start),to=Math.min(now(),midnight(addDays(end,1)));if(from>=to)throw new Error('Choose a date range that starts before now.');return {basis:$('basis').value,from,to,bucket:$('bucket').value,breakdown:$('breakdown').value,limit:$('series-limit').value,forces:[...selected.forces],patches:[...selected.patches],groups:[...selected.groups]};}
async function loadData(){if(!permitted())return;let o;try{o=options();}catch(e){$('data-error').hidden=false;msg('data-error',e.message);return;}save();loadController?.abort();const controller=loadController=new AbortController(),version=epoch;allRows=[];loaded=false;exports.clear();$('charts').hidden=true;$('data-error').hidden=true;msg('load-status','Loading stored releases…');$('reload-data').disabled=true;const rows=[];let last='',expected=null;try{while(true){let query=client.from('police_releases').select('id,force,force_name,patch_ids,published_at,first_seen_at,location_status',last?{}:{count:'exact'}).gte(o.basis,new Date(o.from).toISOString()).lt(o.basis,new Date(o.to).toISOString()).order('id').limit(1000).abortSignal(controller.signal);if(last)query=query.gt('id',last);const r=await bounded(query);if(version!==epoch||controller!==loadController||!permitted())return;if(r.error)throw r.error;if(!last){if(!Number.isFinite(r.count))throw new Error('The complete release count could not be verified. Please retry.');expected=r.count;}rows.push(...r.data);msg('load-status','Loading… '+rows.length.toLocaleString('en-GB')+' releases read. Charts appear when the whole range is loaded.');if(!r.data.length){if(expected!==null&&rows.length<expected)throw new Error('The stored data changed while loading. Refresh to try again.');break;}if(expected!==null?rows.length>=expected:r.data.length<1000)break;const cursor=r.data.at(-1).id;if(cursor===last)throw new Error('Pagination did not advance. Please retry.');last=cursor;}
 const finalAccess=await bounded(client.rpc('desk_my_access'));if(version!==epoch||controller!==loadController||!permitted())return;if(finalAccess.error||finalAccess.data?.allowed!==true){clearData();waiting(finalAccess.data?.reason||'error');return;}allRows=rows;loaded=true;loadedRange=o;msg('load-status',rows.length.toLocaleString('en-GB')+' stored releases loaded · refreshed '+dateLabel(now()));render();}catch(e){if(version!==epoch||controller!==loadController)return;allRows=[];loaded=false;$('data-error').hidden=false;msg('data-error','Data could not be loaded completely. '+e.message);msg('load-status','No partial results are shown. Use Refresh data to retry.');}finally{if(controller===loadController){loadController=null;$('reload-data').disabled=false;}}}
function download(name,rows){if(!permitted()||!rows)return;const url=URL.createObjectURL(new Blob([csv([['Police Checks — stored release data'],['Count by',loadedRange.basis==='first_seen_at'?'First picked up':'Publication time'],['From (UK)',dateLabel(loadedRange.from)],['To (UK, exclusive)',dateLabel(loadedRange.to)],['Force IDs',[...selected.forces].join('; ')||'All'],['Patch IDs',[...selected.patches].join('; ')||'All'],['Regions',[...selected.groups].join('; ')||'All'],[],...rows])],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='police-'+name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
for(const b of document.querySelectorAll('[data-export]'))b.onclick=()=>download(b.dataset.export,exports.get(b.dataset.export));
function render(){if(!loaded||!permitted())return;let o;try{o={...loadedRange,bucket:$('bucket').value,breakdown:$('breakdown').value,limit:$('series-limit').value,forces:[...selected.forces],patches:[...selected.patches],groups:[...selected.groups]};$('data-error').hidden=true;const rows=filterRows(allRows,o,maps),daily=new Map();for(const r of rows){const key=ukParts(Date.parse(r[o.basis])).date;daily.set(key,(daily.get(key)||0)+1);}const peak=[...daily].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0];msg('metric-total',rows.length.toLocaleString('en-GB'));msg('metric-forces',new Set(rows.map(r=>r.force)).size);msg('metric-peak',peak?peak[0]:'—');msg('metric-peak-detail',peak?peak[1]+' releases':'No matching releases');
 const pattern=averagePattern(rows,o,Date.parse(archive.first_seen_at)),averageRows=rows.filter(r=>{const t=Date.parse(r[o.basis]);return pattern.dayCount&&t>=midnight(pattern.first)&&t<midnight(addDays(pattern.last,1));});msg('metric-average',pattern.dayCount?(averageRows.length/pattern.dayCount).toLocaleString('en-GB',{maximumFractionDigits:1}):'—');msg('metric-average-detail',pattern.dayCount+' complete days in the average');
 msg('coverage-note','Stored history only. First recorded arrival: '+(archive.first_seen_at?dateLabel(Date.parse(archive.first_seen_at)):'none yet')+'. '+(o.basis==='first_seen_at'?'First picked up means first saved by the publisher; an initial import or backlog can create a spike.':'Publication times come from the source data and can be date-only or estimated.')+' This archive cannot prove that collection ran continuously.');
 const time=timeline(rows,o,maps),timelineRows=[['Period',...time.series.map(s=>s.name)],...time.bins.map((b,i)=>[b.label,...time.series.map(s=>s.values[i])])];exports.set('timeline',timelineRows);plot($('timeline-chart'),time.bins.map(b=>b.label),time.series,{type:$('chart-type').value,height:350,description:'Releases over time, '+o.bucket+' buckets',integer:true});table($('timeline-table'),timelineRows);$('timeline-legend').replaceChildren();time.series.forEach((s,i)=>{const a=document.createElement('span'),dot=document.createElement('i');dot.style.background=colours[i%colours.length];a.append(dot,document.createTextNode(s.name));$('timeline-legend').append(a);});msg('overlap-note',(o.breakdown==='patch'||o.breakdown==='group'?'A release can belong to several areas: each area counts it once, so series can add up to more than the unique total. ':'Each release is counted once. ')+(time.other?'Less active series are combined into Other. ':'')+'First and last time buckets may be partial.');
 const hours=Array.from({length:24},(_,i)=>String(i).padStart(2,'0')+':00'),days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
 const compare=$('average-by').value,names=compare==='total'?['All selected releases']:rankings(rows,compare,maps,o).filter(x=>x.count>0).slice(0,Number($('average-limit').value)||Infinity).map(x=>x.name);
 const profiles=names.map(name=>({name,pattern:compare==='total'?pattern:patternForRows(rows.filter(r=>categories(r,compare,maps,o).includes(name)),o.basis,pattern)}));
 const previousHeat=$('heatmap-series').value;$('heatmap-series').replaceChildren();const totalOption=document.createElement('option');totalOption.value='';totalOption.textContent='All selected releases';$('heatmap-series').append(totalOption);if(compare!=='total')for(const {name}of profiles){const option=document.createElement('option');option.value=name;option.textContent=name;$('heatmap-series').append(option);}if(profiles.some(p=>p.name===previousHeat))$('heatmap-series').value=previousHeat;
 const heatProfile=profiles.find(p=>p.name===$('heatmap-series').value)?.pattern||pattern;
 $('average-legend').replaceChildren();profiles.forEach((p,i)=>{const span=document.createElement('span'),dot=document.createElement('i');dot.style.background=colours[i%colours.length];span.append(dot,document.createTextNode(p.name));$('average-legend').append(span);});
 if(pattern.dayCount){plot($('hour-chart'),hours,profiles.map(p=>({name:p.name,values:p.pattern.hours})),{description:'Average releases by UK hour',type:compare==='total'?'bar':'line'});plot($('weekday-chart'),days,profiles.map(p=>({name:p.name,values:p.pattern.days})),{description:'Average releases by weekday',type:compare==='total'?'bar':'line'});heatmap($('heatmap-chart'),heatProfile.heat);}else for(const id of ['hour-chart','weekday-chart','heatmap-chart'])empty($(id),'No complete days of recorded coverage in this range yet.');
 msg('average-note',pattern.dayCount?`Averages use ${pattern.dayCount} complete UK calendar days, ${pattern.first} to ${pattern.last}. Partial days and dates before the first recorded arrival are excluded; zero-release days are included. Weekdays are divided by the number of that weekday observed. Clock changes are handled in UK time; repeated clock hours are combined. Patch and region series may overlap.`:'Choose a range containing complete days after recording began.');
 exports.set('hour',[['UK hour',...profiles.map(p=>p.name)],...hours.map((h,i)=>[h,...profiles.map(p=>p.pattern.hours[i]??'No complete-day coverage')])]);exports.set('weekday',[['Weekday',...profiles.map(p=>p.name),'Complete days'],...days.map((d,i)=>[d,...profiles.map(p=>p.pattern.days[i]??'No complete-day coverage'),pattern.exposure[i]])]);exports.set('heatmap',[['Coverage',$('heatmap-series').value||'All selected releases'],['Weekday',...hours],...days.map((d,i)=>[d,...heatProfile.heat[i].map(v=>v??'No complete-day coverage')])]);
 const ranked=rankings(rows,$('ranking-by').value,maps,o);if($('ranking-order').value==='least')ranked.sort((a,b)=>a.count-b.count||a.name.localeCompare(b.name));const limit=Number($('ranking-limit').value)||ranked.length;rankBars($('ranking-chart'),ranked.slice(0,limit));const rankRows=[['Name','Release count'],...ranked.map(r=>[r.name,r.count])];table($('ranking-table'),rankRows);exports.set('ranking',rankRows);
 const locNames={matched:'Text location matched',review:'Needs review / force-area coverage',unlocated:'No location found',outside:'Outside mapped patches'},locs=Object.entries(locNames).map(([key,name])=>({name,count:rows.filter(r=>r.location_status===key).length}));rankBars($('locations-chart'),locs);exports.set('locations',[['Location status','Release count'],...locs.map(r=>[r.name,r.count])]);$('charts').hidden=false;
 }catch(e){$('charts').hidden=true;exports.clear();$('data-error').hidden=false;msg('data-error',e.message);}}
$('range').onchange=()=>{setDates();loadData();};$('basis').onchange=()=>{setDates();loadData();};for(const id of ['date-from','date-to'])$(id).onchange=()=>{$('range').value='custom';};$('apply-dates').onclick=loadData;$('reload-data').onclick=loadData;
for(const id of ['bucket','breakdown','series-limit','chart-type','ranking-by','ranking-order','ranking-limit','average-by','average-limit','heatmap-series'])$(id).onchange=()=>{save();render();};
$('reset-data-filters').onclick=()=>{for(const k of Object.keys(selected)){selected[k].clear();for(const b of $(k+'-picker').querySelectorAll('input[type=checkbox]'))b.checked=false;}counts();save();render();};
client.auth.onAuthStateChange((event,next)=>{if(event==='TOKEN_REFRESHED'){session=next;return;}setTimeout(()=>onSession(next),0);});
await pollHealth();const initial=await client.auth.getSession();onSession(initial.data?.session||null);setInterval(pollHealth,30000);setInterval(renderHealth,1000);setInterval(checkAccess,10000);
const resume=()=>{if(!session)return;if(!permitted()){clearData();waiting('check');}checkAccess();};document.addEventListener('visibilitychange',()=>{if(!document.hidden)resume();});window.addEventListener('pageshow',e=>{if(e.persisted)resume();});
