const clock = new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'});
export function ukParts(ms){const p=Object.fromEntries(clock.formatToParts(ms).map(x=>[x.type,x.value]));return {date:`${p.year}-${p.month}-${p.day}`,hour:Number(p.hour)};}
export function addDays(date,n){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
export function midnight(date){const [y,m,d]=date.split('-').map(Number),wall=Date.UTC(y,m-1,d);let t=wall;for(let i=0;i<2;i++){const p=ukParts(t),[a,b,c]=p.date.split('-').map(Number);t=wall-(Date.UTC(a,b-1,c,p.hour)-t);}return t;}
export function weekday(date){return (new Date(date+'T12:00:00Z').getUTCDay()+6)%7;}
export function bucket(ms,unit){const {date,hour}=ukParts(ms);if(unit==='hour'){const start=Math.floor(ms/3600000)*3600000;return {key:String(start),start,label:date+' '+String(hour).padStart(2,'0')+':00 '+(new Date(start).getUTCHours()===hour?'GMT':'BST')};}let key=date;if(unit==='week')key=addDays(date,-weekday(date));if(unit==='month')key=date.slice(0,7)+'-01';return {key,start:midnight(key),label:unit==='month'?key.slice(0,7):unit==='week'?'Week of '+key:key};}
export function buildBins(from,to,unit){const bins=[];let b=bucket(from,unit);while(b.start<to){if(bins.length>=2000)throw new Error('This range needs more than 2,000 chart points. Choose a larger time bucket or a shorter date range.');bins.push(b);if(unit==='hour')b=bucket(b.start+3600000,unit);else if(unit==='month'){const d=new Date(b.key+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);b=bucket(midnight(d.toISOString().slice(0,10)),unit);}else b=bucket(midnight(addDays(b.key,unit==='week'?7:1)),unit);}return bins;}
export function catalogueMaps(forces,patches){return {forces:new Map(forces.filter(f=>(f.type||'police')==='police').map(f=>[f.key,f.name])),patches:new Map(patches.map(p=>[p.id,p.name])),groups:new Map(patches.map(p=>[p.id,p.group]))};}
export function filterRows(rows,options,maps){const forces=new Set(options.forces||[]),patches=new Set(options.patches||[]),groups=new Set(options.groups||[]);const wanted=new Set(patches);for(const [id,g] of maps.groups)if(groups.has(g))wanted.add(id);return rows.filter(r=>{const t=Date.parse(r[options.basis]);return Number.isFinite(t)&&t>=options.from&&t<options.to&&(!forces.size||forces.has(r.force))&&(!wanted.size||(r.patch_ids||[]).some(p=>wanted.has(p)));});}
export function categories(row,by,maps,options={}){if(by==='total')return ['All releases'];if(by==='force')return [maps.forces.get(row.force)||row.force_name||row.force||'Unknown force'];let ids=[...new Set(row.patch_ids||[])];const chosen=new Set(options.patches||[]),groups=new Set(options.groups||[]);if(chosen.size||groups.size)ids=ids.filter(id=>chosen.has(id)||groups.has(maps.groups.get(id)));if(by==='patch')return ids.length?ids.map(id=>maps.patches.get(id)||id):['No mapped patch'];return [...new Set(ids.map(id=>maps.groups.get(id)||'Unmapped region'))].length?[...new Set(ids.map(id=>maps.groups.get(id)||'Unmapped region'))]:['No mapped region'];}
export function rankings(rows,by,maps,options={}){const count=new Map();if(by==='force')for(const [key,name] of maps.forces)if(!options.forces?.length||options.forces.includes(key))count.set(name,0);for(const r of rows)for(const name of new Set(categories(r,by,maps,options)))count.set(name,(count.get(name)||0)+1);return [...count].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));}
export function timeline(rows,options,maps){const bins=buildBins(options.from,options.to,options.bucket);const by=options.breakdown;const ranked=rankings(rows,by,maps,options).filter(x=>x.count>0);const limit=Number(options.limit)||ranked.length;const names=ranked.slice(0,limit).map(x=>x.name);if(by==='total'&&!names.length)names.push('All releases');const other=ranked.length>names.length;if(other)names.push('Other');const series=names.map(name=>({name,values:new Array(bins.length).fill(0)})),indexes=new Map(bins.map((b,i)=>[b.key,i])),seriesIndex=new Map(names.map((n,i)=>[n,i]));for(const r of rows){const index=indexes.get(bucket(Date.parse(r[options.basis]),options.bucket).key);if(index===undefined)continue;const assigned=new Set(categories(r,by,maps,options).map(n=>seriesIndex.has(n)?n:'Other'));for(const name of assigned){const i=seriesIndex.get(name);if(i!==undefined)series[i].values[index]++;}}return {bins,series,other};}
export function averagePattern(rows,options,coverageStart){if(!Number.isFinite(coverageStart))return {hours:Array(24).fill(null),days:Array(7).fill(null),heat:Array.from({length:7},()=>Array(24).fill(null)),dayCount:0,first:null,last:null,exposure:Array(7).fill(0)};let first=ukParts(options.from).date;if(midnight(first)<options.from)first=addDays(first,1);if(Number.isFinite(coverageStart)){let c=ukParts(coverageStart).date;if(midnight(c)<coverageStart)c=addDays(c,1);if(c>first)first=c;}const last=ukParts(options.to).date;const start=midnight(first),end=midnight(last);const hours=Array(24).fill(0),days=Array(7).fill(0),heat=Array.from({length:7},()=>Array(24).fill(0)),hd=Array(24).fill(0),dd=Array(7).fill(0),he=Array.from({length:7},()=>Array(24).fill(0));let dayCount=0;for(let date=first;date<last;date=addDays(date,1)){if(++dayCount>40000)throw new Error('Date range too large.');const dow=weekday(date);dd[dow]++;const present=new Set();for(let t=midnight(date);t<midnight(addDays(date,1));t+=3600000)present.add(ukParts(t).hour);for(const h of present){hd[h]++;he[dow][h]++;}}
 for(const r of rows){const t=Date.parse(r[options.basis]);if(t<start||t>=end)continue;const p=ukParts(t),d=weekday(p.date);hours[p.hour]++;days[d]++;heat[d][p.hour]++;}return {hours:hours.map((v,i)=>hd[i]?v/hd[i]:null),days:days.map((v,i)=>dd[i]?v/dd[i]:null),heat:heat.map((a,d)=>a.map((v,h)=>he[d][h]?v/he[d][h]:null)),dayCount,first,last:dayCount?addDays(last,-1):null,exposure:dd,hourExposure:hd,heatExposure:he,from:start,to:end};}
export function csv(rows){return rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');}

export function patternForRows(rows,basis,window){if(!window.dayCount)return window;const hours=Array(24).fill(0),days=Array(7).fill(0),heat=Array.from({length:7},()=>Array(24).fill(0));for(const row of rows){const t=Date.parse(row[basis]);if(t<window.from||t>=window.to)continue;const p=ukParts(t),d=weekday(p.date);hours[p.hour]++;days[d]++;heat[d][p.hour]++;}return {...window,hours:hours.map((v,h)=>window.hourExposure[h]?v/window.hourExposure[h]:null),days:days.map((v,d)=>window.exposure[d]?v/window.exposure[d]:null),heat:heat.map((a,d)=>a.map((v,h)=>window.heatExposure[d][h]?v/window.heatExposure[d][h]:null))};}
